### ISSUE TITLE
Continue processing even if one process is crashing

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing#18]
Because of https://github.com/courtois-neuromod/anat-processing/issues/17, every time i run the pipeline it eventually crashes, which makes the addition of processes difficult: i cannot test them because the pipeline crashes before...

@agahkarakuzu is there a way to ignore crashes of a process/subject?

**Comment by jcohenadad** [comment]
for now my workaround is to rename the problematic subject as "_sub-06_ses-002_rec-dis2d_bp-cspine_T2w.nii.gz" so it is ignored...

**Comment by agahkarakuzu** [comment]
@jcohenadad you can see the error handling strategies [here](https://www.nextflow.io/docs/latest/process.html#errorstrategy). 

```
errorStrategy 'ignore'
```

 Adding this directive to the process description (i.e. in a module) could achieve that.

**Comment by agahkarakuzu** [comment]
SCT is no longer using Nextflow, closing the issue.
