### ISSUE TITLE
User access: grant write privileges to user mathieuboudreau

### ISSUE THREAD

**Issue by mathieuboudreau** [courtois-neuromod/anat-processing#32]
@agahkarakuzu @jcohenadad @bpinsard @pbellec If someone could grant me write privileges to this repo, that would be appreciated. I need it to update the README and publish new data releases.

**Comment by bpinsard** [comment]
Set write permissions for your account, reopen if you have issues.

**Comment by mathieuboudreau** [comment]
Perfect, thanks @bpinsard  🙏 !
