### ISSUE TITLE
Update nextflow pipeline to add processing

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing#7]
### Context

The initial NF pipeline started with the MTsat pipeline copied from [this repos](https://github.com/qMRLab/qMRFlow/blob/master/mt_sat/nextflow.config).

We need to add the following processing:

- DWI
  - Currently there is a tractoflow pipeline, that outputs DTI maps and performs tractography
- MTR
  - registration to T1w MPRAGE (so we can use the masks)
- T1 mapping from the MP2RAGE data
- Spinal Cord: process MTR/sat, DWI, 
- Extraction of metrics: will be done in notebook, see https://github.com/courtois-neuromod/anat-processing/issues/3

**Comment by agahkarakuzu** [comment]
SCT is no longer using Nextflow, closing the issue.
